### ISSUE TITLE
Logstash not starting due to error

### ISSUE THREAD

**Issue by skluthe** [3ilson/ansible-pfelk#3]
Followed your ansible install and everything is working except for logstash. I'm getting this error:
```
ERROR] 2020-03-13 20:55:28.125 [[main]-pipeline-manager] javapipeline - Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<RuntimeError: Grok pattern file does not exist: /etc/logstash/conf.d/patterns/pf-12.2019.grok>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.2.0/lib/logstash/filters/grok.rb:445:in `block in add_patterns_from_files'", "org/jruby/RubyArray.java:1814:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.2.0/lib/logstash/filters/grok.rb:443:in `add_patterns_from_files'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.2.0/lib/logstash/filters/grok.rb:282:in `block in register'", "org/jruby/RubyArray.java:1814:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.2.0/lib/logstash/filters/grok.rb:278:in `block in register'", "org/jruby/RubyHash.java:1428:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.2.0/lib/logstash/filters/grok.rb:273:in `register'", "org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:56:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:200:in `block in register_plugins'", "org/jruby/RubyArray.java:1814:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:199:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:502:in `maybe_setup_out_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:212:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:154:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:109:in `block in start'"], "pipeline.sources"=>["/etc/logstash/conf.d/01-inputs.conf", "/etc/logstash/conf.d/11-firewall.conf", "/etc/logstash/conf.d/12-suricata.conf", "/etc/logstash/conf.d/13-snort.conf", "/etc/logstash/conf.d/15-others.conf", "/etc/logstash/conf.d/20-geoip.conf", "/etc/logstash/conf.d/50-outputs.conf"], :thread=>"#<Thread:0x4ec02327 run>"}
[ERROR] 2020-03-13 20:55:28.146 [Converge PipelineAction::Create<main>] agent - Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Create<main>, action_result: false", :backtrace=>nil}
```

**Comment by fktkrt** [comment]
Can you paste here the relevant part of your logstash log?
Its location could vary, but you can try this first: `/var/log/logstash-plain.log`

**Comment by skluthe** [comment]
I'll have to wait until Monday as it's not accessible when not at the
office. I'll post it as soon as I can.

**Comment by skluthe** [comment]
```
[2020-03-16T14:04:56,984][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.6.1"}
[2020-03-16T14:05:01,133][INFO ][org.reflections.Reflections] Reflections took 45 ms to scan 1 urls, producing 20 keys and 40 values
[2020-03-16T14:05:02,262][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2020-03-16T14:05:02,513][WARN ][logstash.outputs.elasticsearch][main] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2020-03-16T14:05:02,596][INFO ][logstash.outputs.elasticsearch][main] ES Output version determined {:es_version=>7}
[2020-03-16T14:05:02,602][WARN ][logstash.outputs.elasticsearch][main] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2020-03-16T14:05:02,731][INFO ][logstash.outputs.elasticsearch][main] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://localhost:9200"]}
[2020-03-16T14:05:02,752][INFO ][logstash.filters.geoip   ][main] Using geoip database {:path=>"/usr/share/GeoIP/GeoLite2-City.mmdb"}
[2020-03-16T14:05:02,829][INFO ][logstash.filters.geoip   ][main] Using geoip database {:path=>"/usr/share/GeoIP/GeoLite2-ASN.mmdb"}
[2020-03-16T14:05:02,827][INFO ][logstash.outputs.elasticsearch][main] Using default mapping template
[2020-03-16T14:05:02,913][INFO ][logstash.outputs.elasticsearch][main] Attempting to install template {:manage_template=>{"index_patterns"=>"logstash-*", "version"=>60001, "settings"=>{"index.refresh_interval"=>"5s", "number_of_shards"=>1}, "mappings"=>{"dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false, "fields"=>{"keyword"=>{"type"=>"keyword", "ignore_above"=>256}}}}}], "properties"=>{"@timestamp"=>{"type"=>"date"}, "@version"=>{"type"=>"keyword"}, "geoip"=>{"dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip"}, "location"=>{"type"=>"geo_point"}, "latitude"=>{"type"=>"half_float"}, "longitude"=>{"type"=>"half_float"}}}}}}}
[2020-03-16T14:05:02,986][ERROR][logstash.javapipeline    ][main] Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<RuntimeError: Grok pattern file does not exist: /etc/logstash/conf.d/patterns/pf-12.2019.grok>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.2.0/lib/logstash/filters/grok.rb:445:in `block in add_patterns_from_files'", "org/jruby/RubyArray.java:1814:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.2.0/lib/logstash/filters/grok.rb:443:in `add_patterns_from_files'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.2.0/lib/logstash/filters/grok.rb:282:in `block in register'", "org/jruby/RubyArray.java:1814:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.2.0/lib/logstash/filters/grok.rb:278:in `block in register'", "org/jruby/RubyHash.java:1428:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-grok-4.2.0/lib/logstash/filters/grok.rb:273:in `register'", "org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:56:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:200:in `block in register_plugins'", "org/jruby/RubyArray.java:1814:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:199:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:502:in `maybe_setup_out_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:212:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:154:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:109:in `block in start'"], "pipeline.sources"=>["/etc/logstash/conf.d/01-inputs.conf", "/etc/logstash/conf.d/11-firewall.conf", "/etc/logstash/conf.d/12-suricata.conf", "/etc/logstash/conf.d/13-snort.conf", "/etc/logstash/conf.d/15-others.conf", "/etc/logstash/conf.d/20-geoip.conf", "/etc/logstash/conf.d/50-outputs.conf"], :thread=>"#<Thread:0x7809577d run>"}
[2020-03-16T14:05:03,003][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Create<main>, action_result: false", :backtrace=>nil}
[2020-03-16T14:05:03,282][INFO ][logstash.runner          ] Logstash shut down.
```

**Comment by skluthe** [comment]
Permissions of /etc/logstash/conf.d/patterns/pf-12.2019.grok are 777 and owned by logstash although everything else in /etc/logstash is owned by root.

**Comment by skluthe** [comment]
@revere521 @fktkrt Sorry to tag you guys but I'm trying to get this up asap. Just moved all our employees remote due to crona virus concerns and need to keep a close eye on pfsense to make sure it's not getting overwhelmed.

**Comment by revere521** [comment]
Sorry, i'm also doing some work to manage our wfh employees, been a busy few days.  It does look like the configurations specifically set the ownership of the .grok file at root:root 0640.  Does changing it back to default net any benefit? 

Possibly the patterns dir needs +x permissions too, can you check that?

**Comment by skluthe** [comment]
Setting the patterns directory to be executable resolved this issue. It
still looks as though the grok patterns aren't being used. The other issue
I opened is relating to that though.

**Comment by skluthe** [comment]
Thanks for getting back to me even though you've been busy. I really
appreciate this project and would be happy to help out with it once I've
got some breathing room at work (going to be a bit hectic for a while and
I'm sure yours will be too)

**Comment by revere521** [comment]
Glad that worked!, and no problem at all.  

It could take some time to populate field data, you can also go to Settings -> Index Patterns -> pf-* and refresh the index to "gather" all the new fields that the pattern is detecting

**Comment by fktkrt** [comment]
> Permissions of /etc/logstash/conf.d/patterns/pf-12.2019.grok are 777 and owned by logstash although everything else in /etc/logstash is owned by root.

Yes, sorry about that. There was formatting issue with the given ansible task, that caused setting wrong access mode on those files. It is taken care of, the changes are committed.

I am closing this issue, please let us know if you encounter further issues.
